name: .NET Publish to NuGet

on:
  push:
    branches: [ "main" ]
  release:
    types: [ published, edited, released, deleted, unpublished ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies for all projects
        run: |
          dotnet restore ./GenerateVerticalSliceArchitecture
          dotnet restore ./GenerateVerticalSliceArchitecture.FluentResults

      - name: Build all projects
        run: |
          dotnet build ./GenerateVerticalSliceArchitecture --configuration Release --no-restore
          dotnet build ./GenerateVerticalSliceArchitecture.FluentResults --configuration Release --no-restore

      - name: Pack GenerateVerticalSliceArchitecture
        run: dotnet pack ./GenerateVerticalSliceArchitecture --configuration Release --output ./nupkg

      - name: Pack GenerateVerticalSliceArchitecture.FluentResults
        run: dotnet pack ./GenerateVerticalSliceArchitecture.FluentResults --configuration Release --output ./nupkg

      - name: Publish all packages to NuGet
        run: dotnet nuget push ./nupkg/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
